### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by philip-peterson** [somekindofwallflower/somekindofwallflower#7]
Hello! Thanks for following me. I am always happy to help fellow students of the craft learn more about JS and such. Was there a particular project that pointed you toward me that you had an interest in?

Cheers,
Philip

**Comment by somekindofwallflower** [comment]
Hello Philip, thank you for taking the time to write me down! Your profile piqued my curiosity, but to be honest, I didn't have the time to thoroughly check your repositories; nonetheless, I will let you know! Please feel free to write/suggest if you have any questions or suggestions concerning my repos here.

**Comment by somekindofwallflower** [comment]
> Hello! Thanks for following me. I am always happy to help fellow students of the craft learn more about JS and such. Was there a particular project that pointed you toward me that you had an interest in?
> 
> Cheers, Philip

Hello Philip, thank you for taking the time to write me down! Your profile piqued my curiosity, but to be honest, I didn't have the time to thoroughly check your repositories; nonetheless, I will let you know! Please feel free to write/suggest if you have any questions or suggestions concerning my repos here.
