### ISSUE TITLE
Would you collabrate with me for a JS project

### ISSUE THREAD

**Issue by Denver44** [somekindofwallflower/somekindofwallflower#9]
Hello @somekindofwallflower I would like to know are you interested in a javascript project, because I m looking for someone with whom I can collaborate on a project and master my js skills, right now I m planning to build a project using tech stack like next, react, ts and scss for frontend and for backend right now it is in js but in 2 to 3 month, I am planning  to change it to typescript or migrate it to loopback so, if u are interested in collaborating then please let me know, I saw your profile it is awesome and this is the project link which I m going to build https://github.com/Denver44/Natours-MERN-App currently the frontend is built using pug template but we will change to next 

Frontend Code : - https://github.com/Denver44/Natours-NextJs
Backend Code  :-   https://github.com/Denver44/Natours-MERN-App 

Currently, for the front end, I set up the boilerplate code and in two to three days we will start if you are interested.
The code and folder structure will be the same as we have in the industry, so we will make this app full production-ready

**Comment by somekindofwallflower** [comment]
Hello @Denver44 Thank you for writing to me! I would like to collaborate in your project with a condition that we include in the project @formidablae https://github.com/formidablae What do you think?

**Comment by Denver44** [comment]
Yeah no problem, more the number of people more we will learn how to collaborate and work and plus we can do a lot more stuff in our web app as the task will be divided among each three of us, so no issue for me and if he wants to collaborate he can, but as it initial days so if it's you, me and  @formidablae it will be okay once we three, masters js after then we will start making some real project or problem-solving app and in which if more people want to join they can join us what you say?

**Comment by formidablae** [comment]
Hello all. I would be very pleased to work with you on the project or even other future projects. Let's make a telegram group where we can start chatting. Join here: https://t.me/+KEruejH0Jzs2ZDIx

**Comment by Denver44** [comment]
> Hello all. I would be very pleased to work with you on the project or even other future projects. Let's make a telegram group where we can start chatting. Join here: https://t.me/+KEruejH0Jzs2ZDIx

I have requested to join the telegram group so please approve it

**Comment by somekindofwallflower** [comment]
> > Hello all. I would be very pleased to work with you on the project or even other future projects. Let's make a telegram group where we can start chatting. Join here: https://t.me/+KEruejH0Jzs2ZDIx
> 
> I have requested to join the telegram group so please approve it

Done, we can chat on Telegram from now on! :)
